# Site settings
title: Unfreeze Eclipse
tag_text: Unfreeze Eclipse
description: Stop killing your IDE! Unfreeze your Eclipse now!
url: "http://unfreezeeclipse.com"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
